services:
  ollama:
    container_name: ollama
    image: ollama/ollama

    # runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      OLLAMA_KV_CACHE_TYPE: "q4_0"
      OLLAMA_KEEP_ALIVE: "24h"
      OLLAMA_MAX_LOADED_MODELS: "1"
      OLLAMA_FLASH_ATTENTION: "1"
    # shm_size: 2g
    healthcheck:
      test: [ "CMD", "ollama", "list", "||", "exit", "1" ]
      interval: 60s
      timeout: 30s
      retries: 5

    ports:
     - "11434:11434"
      # - "127.0.0.1:11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    entrypoint: /bin/sh -c "ollama serve & sleep 3 && ollama pull ${LLM_MODEL} && wait"

volumes:
  ollama:
